### ISSUE TITLE
How it works?

### ISSUE THREAD

**Issue by TheBalkanDev** [DaisukeDaisukeTeam/BuyLand#1]
Can you make a better README?

**Comment by DaisukeDaisuke** [comment]
I'm sorry.
This plugin does not work.
Would you please use the following plugin instead?

> https://www.google.com/search?q=site%3Apoggit.pmmp.io+world+protect 
# better world protect plugins
## iProtector
https://poggit.pmmp.io/p/iProtector/
## WorldProtect
 https://poggit.pmmp.io/p/WorldProtect
## WorldGuard
https://poggit.pmmp.io/p/WorldGuard
